# Generated by Django 5.0.6 on 2024-07-10 06:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("part3", "0002_remove_project_student_remove_student_email_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Student",
            new_name="Students",
        ),
    ]
